using System.Windows.Markup;

[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Controls")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Converters")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Extensions")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Geometry")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Input")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Interop")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Mdi")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Media")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Numerics")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Shapes")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Threading")]
[assembly: XmlnsDefinition("http://schema.butler.software/rhombus", "Rhombus.Wpf.Airspace.Utilities")]